// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PetAdoptionProject.Data;

#nullable disable

namespace PetAdoptionProject.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240411003548_Fourth")]
    partial class Fourth
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PetAdoptionProject.Models.ClientDB", b =>
                {
                    b.Property<int>("ClientID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClientID"));

                    b.Property<int?>("AnimalID")
                        .HasColumnType("int");

                    b.Property<string>("ClientAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PetType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClientID");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            ClientID = 1,
                            AnimalID = 84,
                            ClientAddress = "Goris",
                            Email = "anigilavyan@gmail.com",
                            FirstName = "Ani",
                            LastName = "Gilavyan",
                            Password = "anianiani",
                            PetType = "dog",
                            PhoneNumber = "2255526852"
                        },
                        new
                        {
                            ClientID = 2,
                            AnimalID = 42,
                            ClientAddress = "Goris",
                            Email = "manushatasunts@gmail.com",
                            FirstName = "Artyom",
                            LastName = "Gilavyan",
                            Password = "mamamama",
                            PetType = "pig",
                            PhoneNumber = "852565"
                        });
                });

            modelBuilder.Entity("PetAdoptionProject.Models.NourishmentDB", b =>
                {
                    b.Property<int>("NourishID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NourishID"));

                    b.Property<string>("Brand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NourishName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Price")
                        .HasColumnType("int");

                    b.HasKey("NourishID");

                    b.ToTable("Nourishments");

                    b.HasData(
                        new
                        {
                            NourishID = 1,
                            Brand = "DogNour",
                            NourishName = "MommyDoggy",
                            Price = 100
                        },
                        new
                        {
                            NourishID = 2,
                            Brand = "YumDog",
                            NourishName = "DogSnack",
                            Price = 200
                        },
                        new
                        {
                            NourishID = 3,
                            Brand = "PetYummas",
                            NourishName = "Yummy",
                            Price = 300
                        });
                });

            modelBuilder.Entity("PetAdoptionProject.Models.PetsDB", b =>
                {
                    b.Property<int>("PetID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PetID"));

                    b.Property<string>("PetDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PetName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PetType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PetID");

                    b.ToTable("Pets");

                    b.HasData(
                        new
                        {
                            PetID = 1,
                            PetDescription = "Healthy",
                            PetName = "Rony",
                            PetType = "Dog"
                        },
                        new
                        {
                            PetID = 2,
                            PetDescription = "Healthy",
                            PetName = "Boghar",
                            PetType = "Dog"
                        },
                        new
                        {
                            PetID = 3,
                            PetDescription = "Needs medical care",
                            PetName = "August",
                            PetType = "Dog"
                        });
                });

            modelBuilder.Entity("PetAdoptionProject.Models.UserDB", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<int?>("AnimalID")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PetName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PetType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserAddress")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserID = 1,
                            AnimalID = 12,
                            Email = "arminegilavyan04@gmail.com",
                            FirstName = "Manush",
                            LastName = "Atasunts",
                            Password = "Aniartyom",
                            PetName = "Lola",
                            PetType = "cat",
                            PhoneNumber = "642574",
                            UserAddress = "Goris"
                        },
                        new
                        {
                            UserID = 2,
                            AnimalID = 31,
                            Email = "arminegilavya125n04@gmail.com",
                            FirstName = "Arkadi",
                            LastName = "Gilavyan",
                            Password = "lalala",
                            PetName = "Boghar",
                            PetType = "dog",
                            PhoneNumber = "7547854",
                            UserAddress = "Goris"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
